version: '3'

services:
  database-mysql:
    container_name: database-mysql
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: 'simple'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'GN'
      TZ: Asia/Seoul

    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d

    ports:
      - '13306:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

  spring-gn:
    container_name: spring-gn
    image: spring-gn:latest
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - database-mysql