DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS comment;
-- DROP TABLE IF EXISTS chat;

CREATE TABLE member (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT email_unique UNIQUE (email)
);

CREATE TABLE post (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    writer VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    post_time TIMESTAMP
);

CREATE TABLE comment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    post_id BIGINT,
    writer VARCHAR(255),
    content VARCHAR(255) NOT NULL,
    created_date TIMESTAMP
);

-- CREATE TABLE chat (
--     id BIGINT NOT NULL AUTO_INCREMENT,
--     name VARCHAR(50) NOT NULL,
--     message VARCHAR(1000) NOT NULL,
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id)
-- );




